Fix issue 286 email notification (#311)
* add test for issue #287 AttributeError: 'Settings' object has no attribute 'EMAIL_NOTIFICATION'

* fixes #287 AttributeError: 'Settings' object has no attribute 'EMAIL_NOTIFICATION'

* fixes #287 AttributeError: 'Settings' object has no attribute 'EMAIL_NOTIFICATION'

* Add a test for #290 Domyślny tytuł wiadomości określić

* close #290 Domyślny tytuł wiadomości określić

* Revert "close #290 Domyślny tytuł wiadomości określić"

This reverts commit 472af2b

* Revert "Add a test for #290 Domyślny tytuł wiadomości określić"

This reverts commit 78c197e

* close #286

get email "from" value from env